title: Dota 2 Service Provider
author: MrEkoh
email: MrEkoh@domain.com
description: > # this means to ignore newlines until "baseurl:"
 Proffessional Dota 2 player

# social links
twitter_username: GagAttack
github_username:  MrEkohAttacks

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
